name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterwave: ^0.0.2
  cupertino_icons: ^0.1.3
  http: ^0.13.3
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
